
DELETE FROM TB_SYS_ROLE;
INSERT INTO TB_SYS_ROLE(ROLE_ID,ROLE_NAME,REMARK) VALUES (1, 'admin', '超级管理员');
INSERT INTO TB_SYS_ROLE(ROLE_ID,ROLE_NAME,REMARK) VALUES (-1, '代理', '代理角色');
INSERT INTO TB_SYS_ROLE(ROLE_ID,ROLE_NAME,REMARK) VALUES (-2, '普通会员', '普通会员');

DELETE FROM TB_SYS_LOGIN;
INSERT INTO TB_SYS_LOGIN(LOGINNO,USERNO,LOGINNAME,NICKNAME,LOGINPWD,ISVALID,TYPE) VALUES ('admin', '', '超管', '', '202cb962ac59075b964b07152d234b70', 'Y',-1);

DELETE FROM TB_SYS_USER_ROLE;
INSERT INTO TB_SYS_USER_ROLE(ID,LOGINNO,ROLE_ID) VALUES(1,'admin',1);


INSERT INTO tb_zj_account(ACCTNO,ACCTNAME,MEMO) VALUES ('100', '现金钱包', '现金支付');


INSERT INTO tb_zj_subject(SUNNO,SUBNAME,INOROUT,CALCFIELD,MEMO) VALUES ('100', '上分', 'A', 'A', '转账上分');
INSERT INTO tb_zj_subject(SUNNO,SUBNAME,INOROUT,CALCFIELD,MEMO) VALUES ('101', '下分', 'A', 'B', '提现下分');
INSERT INTO tb_zj_subject(SUNNO,SUBNAME,INOROUT,CALCFIELD,MEMO) VALUES ('102', ',收入', 'A', 'C', '销售收入');
INSERT INTO tb_zj_subject(SUNNO,SUBNAME,INOROUT,CALCFIELD,MEMO) VALUES ('103', '支出', 'A', 'D', '购货支出');
INSERT INTO tb_zj_subject(SUNNO,SUBNAME,INOROUT,CALCFIELD,MEMO) VALUES ('104', '冻结', 'A', 'E', '冻结资金');
INSERT INTO tb_zj_subject(SUNNO,SUBNAME,INOROUT,CALCFIELD,MEMO) VALUES ('105', '解冻', 'B', 'E', '解冻资金');
INSERT INTO tb_zj_subject(SUNNO,SUBNAME,INOROUT,CALCFIELD,MEMO) VALUES ('106', '服务费', 'A', 'D', '平台服务费');

INSERT INTO `tb_sys_para`(`SYSID`, `SYSTYPE`, `GROUPNAME`, `SYSNAME`, `SVAL`, `MEMO`, `ISVALID`, `LASTUPTIME`) VALUES (7, '1', '客户端配置', '安全码', '0768', NULL, 'Y', '2023-12-25 21:19:22');
INSERT INTO `tb_sys_para`(`SYSID`, `SYSTYPE`, `GROUPNAME`, `SYSNAME`, `SVAL`, `MEMO`, `ISVALID`, `LASTUPTIME`) VALUES (8, '1', '客户端配置', '客服地址', '0768', NULL, 'Y', '2023-12-25 21:19:22');
INSERT INTO `tb_sys_para`(`SYSID`, `SYSTYPE`, `GROUPNAME`, `SYSNAME`, `SVAL`, `MEMO`, `ISVALID`, `LASTUPTIME`) VALUES (10, '1', '客户端配置', '校验码', '69q6fq69q6dq68q61q69q6aq6cq61q68q68q68', NULL, 'Y', '2023-12-25 21:19:22');
INSERT INTO `tb_sys_para`(`SYSID`, `SYSTYPE`, `GROUPNAME`, `SYSNAME`, `SVAL`, `MEMO`, `ISVALID`, `LASTUPTIME`) VALUES (11, '1', '客户端配置', '是否暂停运行', 'N', NULL, 'N', '2023-12-25 21:19:22');
INSERT INTO `tb_sys_para`(`SYSID`, `SYSTYPE`, `GROUPNAME`, `SYSNAME`, `SVAL`, `MEMO`, `ISVALID`, `LASTUPTIME`) VALUES (30, '1', '客户端配置', '行情网站地址', 'http://18.212.105.77:8000/eth', NULL, '', '2023-12-25 21:19:22');




