ALTER TABLE tb_data_source ADD COLUMN ISSUE VARCHAR(16) DEFAULT '';


INSERT INTO TB_SYS_MENU(MENU_ID,MENU_NAME,PARENT_ID,MENU_URL,PERMS,TYPE,ICON,ORDER_NO) VALUES('603000','开奖记录','600000','/operations/draw','',1,'el-icon-reading',3);
INSERT INTO TB_SYS_MENU(MENU_ID,MENU_NAME,PARENT_ID,MENU_URL,PERMS,TYPE,ICON,ORDER_NO) VALUES('603001','查看','603000','','operations:draw:view',2,'',1);
INSERT INTO TB_SYS_MENU(MENU_ID,MENU_NAME,PARENT_ID,MENU_URL,PERMS,TYPE,ICON,ORDER_NO) VALUES('603002','下发结算图','603000','','operations:draw:edit',2,'',2);