server:
  port: 8001
  #max-http-header-size: 1024000
  servlet: 
    context-path: /api
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://18.212.105.77:3306/shangcheng?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
      username: root
      password: aNmanwh6WK3e
#      url: jdbc:mysql://16.163.55.65:3306/shangcheng?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
#      username: root
#      password: Rs7jVNoPEEEC
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  servlet: 
    multipart: 
       max-file-size: 10MB  
       max-request-size: 100MB
  redis: 
    host: 18.212.105.77
    port: 6379
    password: tg_pass
    database: 0
    timeout: 10000
    pool: 
      max-active: 200
      max-wait: 10000 
      max-idle: 10
      min-idle: 5
fileService: 
  path:   
sms: 
  sendUrl: 
  secretId: 
  secretKey:  
  signature: 
#后端访问路径
backcore: 
  sendUrl: http://18.212.105.77:8000/apis
heepay: 
  url: 
  agent_id: 
  md5key: 
  deskey: 
  jqmd5key: 
  jqdeskey: 
  querykey: 
  notifyUrl: 
  queryUrl:  
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl